on: 
  push:
    branches:
      - master
  workflow_dispatch:
    
jobs:
  hola_world_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run custom action 
        uses: ./.github/actions
        with:
          who-to-greet: 'Mona the Octocat'
      - run: echo random-number ${{ steps.foo.outputs.random-number }}
        shell: bash
