on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say simple hello
    steps:
      - name: Checkout private tools
        uses: actions/checkout@v2
        with:
         repository: OKiMaureen/test
         token: ${{ secrets.GitHub_PAT }} # `GitHub_PAT` is a secret that contains your PAT
         path: best
