on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    steps:
      - name: custom action test
        uses: actions/checkout@v2
        with:
          repository: okimaureen/test_avtion
          ref: v1
          path: .github/actions/test_avtion
      - name: Run custom action 
        uses: ./.github/actions/test_avtion
        with:
          who-to-greet: 'Mona the Octocat'
      - run: echo random-number ${{ steps.foo.outputs.random-number }}
        shell: bash
