on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    steps:
      - name: custom action testing again
        uses: actions/checkout@v2
        with:
          repository: okimaureen/test_avtion
          path: .github/actions/test_avtion
      - name: Run custom action 
        uses: okimaureen/test/.github/actions/test_avtion@v1
        with:
          who-to-greet: 'Mona the Octocat'
      - run: echo random-number ${{ steps.foo.outputs.random-number }}
        shell: bash
